---
git:
  user: "MDynowska"
  email: "magdalena.dynowskaa@gmail.com"
repository_url: https://github.com/MDynowska/Ansible.git
os_packages:
  - python36
  - python36-pip
  - git
  - tree
  - mc
bucket_name: "kkanclerz-zid"
python_dependencies:
  - boto3
  - pytest
  - flask
app_root_dir: "~/ani-creator"
